server:
  port: 8082

info:
  component: Revenue Composite Service
spring:
 datasource:
#    url: jdbc:mysql://192.168.99.100:3306/pricerevenue
    url: jdbc:mysql://0.0.0.0:3306/pricerevenue
    username: admin
    password: root
    driver-class-name: com.mysql.jdbc.Driver

#eureka:
#  instance:
#    leaseRenewalIntervalInSeconds: 3
#    metadataMap:
#      instanceId: ${vcap.application.instance_id:${spring.application.name}:${spring.application.instance_id:${random.value}}}
#  client:
#    # Default values comes from org.springframework.cloud.netflix.eureka.EurekaClientConfigBean
#    registryFetchIntervalSeconds: 5
#    instanceInfoReplicationIntervalSeconds: 5
#    initialInstanceInfoReplicationIntervalSeconds: 5
#    serviceUrl:
#      defaultZone: http://127.0.0.1:8761/eureka/
#
#logging:
#  level:
#    root: WARN
#    se.callista: INFO
#
#---
## For deployment in Docker containers
#spring:
#  profiles: docker
#
#server:
#  port: 8082
#
#eureka:
#  instance:
#    preferIpAddress: true
#  client:
#    serviceUrl:
#      defaultZone: http://discovery:8761/eureka/
#
#---
## For deployment in Cloud Foundry
#spring:
#  profiles: cloud
#
#eureka:
#  instance:
#    hostname: ${vcap.application.uris[0]:localhost}
#    nonSecurePort: 80
#  client:
#    serviceUrl:
#      defaultZone: http://ml-public-ds-1.cfapps.io/eureka/
